#!/bin/bash
# GPS Cerdas: Mencari folder tempat script ini berada, lalu masuk ke target/
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -Djava.awt.headless=true -jar "$SCRIPT_DIR/target/mawiport-1.0-SNAPSHOT.jar" "$@"